#### R- Matrices

In [1]:
# A sequence is one dimensional vector
vec<- 1:10
print(vec) # Notice that the 1 to 10 are printed as a row.

 [1]  1  2  3  4  5  6  7  8  9 10


In [2]:
#to convert this vec into matrix
m <- matrix(vec)
print(m)    

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10


In [3]:
# we can pass on the additional arugments to matrix function to define the number of cols, filling style etc
m2 <- matrix(vec, nrow = 2) # 2(Rows) X 3(Cols) Matrix
print(m2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


#### By default, matrix is filled with byrow = FALSE.  It means, the filling takes place column wise

In [4]:
# The row wise filling 
m3 <- matrix(vec, nrow = 2, byrow = TRUE)
print(m3)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10


#### We can change the names of the columns with '<i>colnames'</i> function

In [6]:
colnames(m3) <- c('col1', 'col2', 'col3', 'col4', 'col5')
print(m3)

     col1 col2 col3 col4 col5
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10


#### We can change the names of the columns with <i>'row.names'</i> function

In [8]:
row.names(m3) <- c('Row1', 'Row2')
print(m3)

     col1 col2 col3 col4 col5
Row1    1    2    3    4    5
Row2    6    7    8    9   10


####  Building a matrix step by step 

In [17]:
# Let us build a more meaningful matrix with cols and rows
ages = c(45, 50, 60, 48, 32)
names = c('sree', 'laths', 'raju', 'ravi', 'mohan')
mat3<- matrix(ages)
print(m3)

     col1 col2 col3 col4 col5
Row1    1    2    3    4    5
Row2    6    7    8    9   10


In [18]:
#Change the rows names and changing the column name
row.names(mat3) <- names
colnames(mat3) <- c('Ages')
print(mat3)

      Ages
sree    45
laths   50
raju    60
ravi    48
mohan   32


In [19]:
# Adding a column salary to mat3
salary<- c(30000, 50000,80000,20000,60000)
mat3 <- cbind(mat3, salary)
mat3

Ages salary
sree  45   30000 
laths 50   50000 
raju  60   80000 
ravi  48   20000 
mohan 32   60000

In [20]:
# Adding a row to the mat3
Babu <- c(56,35000)
mat3 <- rbind(mat3, Babu)
print(mat3)

      Ages salary
sree    45  30000
laths   50  50000
raju    60  80000
ravi    48  20000
mohan   32  60000
Babu    56  35000


### Matrices - Arithmetic and Logical Operations

In [24]:
# Let us create a 5(Row) X 5(col) Matrix 
mat1 <- matrix(1:25, byrow = TRUE, nrow = 5)
print(mat1)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]   11   12   13   14   15
[4,]   16   17   18   19   20
[5,]   21   22   23   24   25


In [26]:
# Multiply this matrix with a scalar 
print(mat1*10) # Ten folds

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   20   30   40   50
[2,]   60   70   80   90  100
[3,]  110  120  130  140  150
[4,]  160  170  180  190  200
[5,]  210  220  230  240  250


In [27]:
#Devide this matrix with a scalar
print(mat1/2) # Halve this matrix

     [,1] [,2] [,3] [,4] [,5]
[1,]  0.5  1.0  1.5  2.0  2.5
[2,]  3.0  3.5  4.0  4.5  5.0
[3,]  5.5  6.0  6.5  7.0  7.5
[4,]  8.0  8.5  9.0  9.5 10.0
[5,] 10.5 11.0 11.5 12.0 12.5


In [28]:
# adding a number to all the elements 
print(mat1+ 1000)

     [,1] [,2] [,3] [,4] [,5]
[1,] 1001 1002 1003 1004 1005
[2,] 1006 1007 1008 1009 1010
[3,] 1011 1012 1013 1014 1015
[4,] 1016 1017 1018 1019 1020
[5,] 1021 1022 1023 1024 1025


In [29]:
# subtacting a number from all the elements
print(mat1 - 0.5)

     [,1] [,2] [,3] [,4] [,5]
[1,]  0.5  1.5  2.5  3.5  4.5
[2,]  5.5  6.5  7.5  8.5  9.5
[3,] 10.5 11.5 12.5 13.5 14.5
[4,] 15.5 16.5 17.5 18.5 19.5
[5,] 20.5 21.5 22.5 23.5 24.5


In [31]:
# crazy 
print(sqrt(mat1))

         [,1]     [,2]     [,3]     [,4]     [,5]
[1,] 1.000000 1.414214 1.732051 2.000000 2.236068
[2,] 2.449490 2.645751 2.828427 3.000000 3.162278
[3,] 3.316625 3.464102 3.605551 3.741657 3.872983
[4,] 4.000000 4.123106 4.242641 4.358899 4.472136
[5,] 4.582576 4.690416 4.795832 4.898979 5.000000


In [32]:
# logical checks returns the boolean matrix
# check if all the elements one by one are greater than 10
print(mat1>10)

      [,1]  [,2]  [,3]  [,4]  [,5]
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE


#### Matrix to Matrix Mathematical operations. For all these below operations, it is important, that the Matrices are of the same dimensions

In [87]:
matA <- matrix(1:25, byrow = TRUE, nrow = 5)
print(matA)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]   11   12   13   14   15
[4,]   16   17   18   19   20
[5,]   21   22   23   24   25


In [35]:
matB <- matrix(25:1, byrow = T, nrow = 5)
print(matB)

     [,1] [,2] [,3] [,4] [,5]
[1,]   25   24   23   22   21
[2,]   20   19   18   17   16
[3,]   15   14   13   12   11
[4,]   10    9    8    7    6
[5,]    5    4    3    2    1


In [36]:
# Add matA , matB
print(matA+matB)

     [,1] [,2] [,3] [,4] [,5]
[1,]   26   26   26   26   26
[2,]   26   26   26   26   26
[3,]   26   26   26   26   26
[4,]   26   26   26   26   26
[5,]   26   26   26   26   26


In [37]:
#subtract matB from matA
print(matA-matB)

     [,1] [,2] [,3] [,4] [,5]
[1,]  -24  -22  -20  -18  -16
[2,]  -14  -12  -10   -8   -6
[3,]   -4   -2    0    2    4
[4,]    6    8   10   12   14
[5,]   16   18   20   22   24


In [38]:
# Element to element multiplication
#This is not a true Matrix multiplication related to linear algebra
print(matA*matB)

     [,1] [,2] [,3] [,4] [,5]
[1,]   25   48   69   88  105
[2,]  120  133  144  153  160
[3,]  165  168  169  168  165
[4,]  160  153  144  133  120
[5,]  105   88   69   48   25


In [40]:
#Matrix multiplication related to linear algebra
print(matA %*% matB)

     [,1] [,2] [,3] [,4] [,5]
[1,]  175  160  145  130  115
[2,]  550  510  470  430  390
[3,]  925  860  795  730  665
[4,] 1300 1210 1120 1030  940
[5,] 1675 1560 1445 1330 1215


In [42]:
# Element to element Division
#This is not a true Matrix divisin related to linear algebra
print(matA/matB)

          [,1]       [,2]      [,3]       [,4]       [,5]
[1,] 0.0400000 0.08333333 0.1304348  0.1818182  0.2380952
[2,] 0.3000000 0.36842105 0.4444444  0.5294118  0.6250000
[3,] 0.7333333 0.85714286 1.0000000  1.1666667  1.3636364
[4,] 1.6000000 1.88888889 2.2500000  2.7142857  3.3333333
[5,] 4.2000000 5.50000000 7.6666667 12.0000000 25.0000000


In [43]:
#Matrix Division related to linear algebra
print(matA %/% matB)

     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0
[2,]    0    0    0    0    0
[3,]    0    0    1    1    1
[4,]    1    1    2    2    3
[5,]    4    5    7   12   25


### Matrix operations with some functions

#### colSums(), rowSums()

In [88]:
print(matA)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]   11   12   13   14   15
[4,]   16   17   18   19   20
[5,]   21   22   23   24   25


In [89]:
# change the column names and row names 
colnames(matA) <- c('c1', 'c2', 'c3', 'c4', 'c5')
rownames(matA) <- c('r1', 'r2', 'r3', 'r4', 'r5')
print(matA)

   c1 c2 c3 c4 c5
r1  1  2  3  4  5
r2  6  7  8  9 10
r3 11 12 13 14 15
r4 16 17 18 19 20
r5 21 22 23 24 25


In [90]:
print(colSums(matA))

c1 c2 c3 c4 c5 
55 60 65 70 75 


In [91]:
print(rowSums(matA))

 r1  r2  r3  r4  r5 
 15  40  65  90 115 


In [92]:
# Adding these totals to matrix 

In [93]:
matA <- rbind(matA, colSums(matA))
print(matA)

   c1 c2 c3 c4 c5
r1  1  2  3  4  5
r2  6  7  8  9 10
r3 11 12 13 14 15
r4 16 17 18 19 20
r5 21 22 23 24 25
   55 60 65 70 75


In [94]:
matA <- cbind(matA, rowSums(matA))

In [96]:
print(matA)

   c1 c2 c3 c4 c5    
r1  1  2  3  4  5  15
r2  6  7  8  9 10  40
r3 11 12 13 14 15  65
r4 16 17 18 19 20  90
r5 21 22 23 24 25 115
   55 60 65 70 75 325
